server:
  servlet:
    session:
      cookie:
        name: auth-server
        path: /auth
    context-path: /auth
  port: 8081

spring:
  h2:
    console:
      enabled: true
      path: /h2-console
    datasource:
      url: jdbc:h2:file:~/spring-boot-h2-security-db;AUTO_SERVER=TRUE
      username: sa
      password:
      driver-class-name: org.h2.Driver
    jpa:
      hibernate:
        ddl-auto: update
      generate-ddl: true
logging:
  level:
    org.springframework.security.oauth2: DEBUG
