spring:
  security:
    user:
      name: admin
      password: admin
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:file:~/spring-boot-h2-security-db;AUTO_SERVER=TRUE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true








###SSL Configuration
server:
  http:
    port: 8080
  port: 8083
  ssl:
    key-store-password: tomcat
    key-store: classpath:mykeystore.p12
    key-store-type: PKCS12
    key-alias: tomcat
